# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/buildbuddy_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from distantbes.proto.proto import bazel_config_pb2 as proto_dot_bazel__config__pb2
from distantbes.proto.proto import invocation_pb2 as proto_dot_invocation__pb2
from distantbes.proto.proto import user_pb2 as proto_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/buildbuddy_service.proto',
  package='buildbuddy.service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1eproto/buildbuddy_service.proto\x12\x12\x62uildbuddy.service\x1a\x18proto/bazel_config.proto\x1a\x16proto/invocation.proto\x1a\x10proto/user.proto2\x80\x04\n\x11\x42uildBuddyService\x12T\n\rGetInvocation\x12 .invocation.GetInvocationRequest\x1a!.invocation.GetInvocationResponse\x12]\n\x10SearchInvocation\x12#.invocation.SearchInvocationRequest\x1a$.invocation.SearchInvocationResponse\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12[\n\x0eGetBazelConfig\x12#.bazel_config.GetBazelConfigRequest\x1a$.bazel_config.GetBazelConfigResponse\x12`\n\x11GetInvocationStat\x12$.invocation.GetInvocationStatRequest\x1a%.invocation.GetInvocationStatResponseb\x06proto3'
  ,
  dependencies=[proto_dot_bazel__config__pb2.DESCRIPTOR,proto_dot_invocation__pb2.DESCRIPTOR,proto_dot_user__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BUILDBUDDYSERVICE = _descriptor.ServiceDescriptor(
  name='BuildBuddyService',
  full_name='buildbuddy.service.BuildBuddyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=635,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInvocation',
    full_name='buildbuddy.service.BuildBuddyService.GetInvocation',
    index=0,
    containing_service=None,
    input_type=proto_dot_invocation__pb2._GETINVOCATIONREQUEST,
    output_type=proto_dot_invocation__pb2._GETINVOCATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchInvocation',
    full_name='buildbuddy.service.BuildBuddyService.SearchInvocation',
    index=1,
    containing_service=None,
    input_type=proto_dot_invocation__pb2._SEARCHINVOCATIONREQUEST,
    output_type=proto_dot_invocation__pb2._SEARCHINVOCATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateUser',
    full_name='buildbuddy.service.BuildBuddyService.CreateUser',
    index=2,
    containing_service=None,
    input_type=proto_dot_user__pb2._CREATEUSERREQUEST,
    output_type=proto_dot_user__pb2._CREATEUSERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='buildbuddy.service.BuildBuddyService.GetUser',
    index=3,
    containing_service=None,
    input_type=proto_dot_user__pb2._GETUSERREQUEST,
    output_type=proto_dot_user__pb2._GETUSERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBazelConfig',
    full_name='buildbuddy.service.BuildBuddyService.GetBazelConfig',
    index=4,
    containing_service=None,
    input_type=proto_dot_bazel__config__pb2._GETBAZELCONFIGREQUEST,
    output_type=proto_dot_bazel__config__pb2._GETBAZELCONFIGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInvocationStat',
    full_name='buildbuddy.service.BuildBuddyService.GetInvocationStat',
    index=5,
    containing_service=None,
    input_type=proto_dot_invocation__pb2._GETINVOCATIONSTATREQUEST,
    output_type=proto_dot_invocation__pb2._GETINVOCATIONSTATRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUILDBUDDYSERVICE)

DESCRIPTOR.services_by_name['BuildBuddyService'] = _BUILDBUDDYSERVICE

# @@protoc_insertion_point(module_scope)
