# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/context.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from distantbes.proto.proto import user_id_pb2 as proto_dot_user__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/context.proto',
  package='context',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13proto/context.proto\x12\x07\x63ontext\x1a\x13proto/user_id.proto\"/\n\x0eRequestContext\x12\x1d\n\x07user_id\x18\x01 \x01(\x0b\x32\x0c.user.UserId\"\x11\n\x0fResponseContextb\x06proto3'
  ,
  dependencies=[proto_dot_user__id__pb2.DESCRIPTOR,])




_REQUESTCONTEXT = _descriptor.Descriptor(
  name='RequestContext',
  full_name='context.RequestContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='context.RequestContext.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=100,
)


_RESPONSECONTEXT = _descriptor.Descriptor(
  name='ResponseContext',
  full_name='context.ResponseContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=119,
)

_REQUESTCONTEXT.fields_by_name['user_id'].message_type = proto_dot_user__id__pb2._USERID
DESCRIPTOR.message_types_by_name['RequestContext'] = _REQUESTCONTEXT
DESCRIPTOR.message_types_by_name['ResponseContext'] = _RESPONSECONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestContext = _reflection.GeneratedProtocolMessageType('RequestContext', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCONTEXT,
  '__module__' : 'proto.context_pb2'
  # @@protoc_insertion_point(class_scope:context.RequestContext)
  })
_sym_db.RegisterMessage(RequestContext)

ResponseContext = _reflection.GeneratedProtocolMessageType('ResponseContext', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECONTEXT,
  '__module__' : 'proto.context_pb2'
  # @@protoc_insertion_point(class_scope:context.ResponseContext)
  })
_sym_db.RegisterMessage(ResponseContext)


# @@protoc_insertion_point(module_scope)
