# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user_id.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/user_id.proto',
  package='user',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13proto/user_id.proto\x12\x04user\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x04Name\x12\x0c\n\x04\x66ull\x18\x01 \x01(\t\x12\r\n\x05\x66irst\x18\x02 \x01(\t\x12\x0c\n\x04last\x18\x03 \x01(\t\"a\n\x0b\x44isplayUser\x12\x1d\n\x07user_id\x18\x01 \x01(\x0b\x32\x0c.user.UserId\x12\x18\n\x04name\x18\x02 \x01(\x0b\x32\n.user.Name\x12\x19\n\x11profile_image_url\x18\x03 \x01(\tb\x06proto3'
)




_USERID = _descriptor.Descriptor(
  name='UserId',
  full_name='user.UserId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='user.UserId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=49,
)


_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='user.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='full', full_name='user.Name.full', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first', full_name='user.Name.first', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last', full_name='user.Name.last', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=100,
)


_DISPLAYUSER = _descriptor.Descriptor(
  name='DisplayUser',
  full_name='user.DisplayUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='user.DisplayUser.user_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='user.DisplayUser.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_image_url', full_name='user.DisplayUser.profile_image_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=199,
)

_DISPLAYUSER.fields_by_name['user_id'].message_type = _USERID
_DISPLAYUSER.fields_by_name['name'].message_type = _NAME
DESCRIPTOR.message_types_by_name['UserId'] = _USERID
DESCRIPTOR.message_types_by_name['Name'] = _NAME
DESCRIPTOR.message_types_by_name['DisplayUser'] = _DISPLAYUSER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'proto.user_id_pb2'
  # @@protoc_insertion_point(class_scope:user.UserId)
  })
_sym_db.RegisterMessage(UserId)

Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'proto.user_id_pb2'
  # @@protoc_insertion_point(class_scope:user.Name)
  })
_sym_db.RegisterMessage(Name)

DisplayUser = _reflection.GeneratedProtocolMessageType('DisplayUser', (_message.Message,), {
  'DESCRIPTOR' : _DISPLAYUSER,
  '__module__' : 'proto.user_id_pb2'
  # @@protoc_insertion_point(class_scope:user.DisplayUser)
  })
_sym_db.RegisterMessage(DisplayUser)


# @@protoc_insertion_point(module_scope)
